// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.flutter_full_screen_scanner_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class ScanModeData(val raw: Int) {
  BARCODE(0),
  QR(1),
  ALL(2);

  companion object {
    fun ofRaw(raw: Int): ScanModeData? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BarcodeFormatData(val raw: Int) {
  ALL_FORMATS(0),
  CODE128(1),
  CODE39(2),
  CODE93(3),
  CODA_BAR(4),
  DATA_MATRIX(5),
  EAN13(6),
  EAN8(7),
  ITF(8),
  QR_CODE(9),
  UPC_A(10),
  UPC_E(11),
  PDF417(12),
  AZTEC(13);

  companion object {
    fun ofRaw(raw: Int): BarcodeFormatData? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ScanWindowData (
  val widthFactor: Double? = null,
  val heightFactor: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScanWindowData {
      val widthFactor = pigeonVar_list[0] as Double?
      val heightFactor = pigeonVar_list[1] as Double?
      return ScanWindowData(widthFactor, heightFactor)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      widthFactor,
      heightFactor,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ScanWindowData
    return MessagesPigeonUtils.deepEquals(this.widthFactor, other.widthFactor) && MessagesPigeonUtils.deepEquals(this.heightFactor, other.heightFactor)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.widthFactor)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.heightFactor)
    return result
  }
  override fun toString(): String {
    return "ScanWindowData(widthFactor=$widthFactor, heightFactor=$heightFactor)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ScannerOptionsData (
  val scanMode: ScanModeData? = null,
  val continuous: Boolean? = null,
  val enableFlash: Boolean? = null,
  val enableGallery: Boolean? = null,
  val enableCameraSwitch: Boolean? = null,
  val enableBeep: Boolean? = null,
  val enableVibration: Boolean? = null,
  val enableImageCapture: Boolean? = null,
  val enableImageAnnotation: Boolean? = null,
  val allowDuplicate: Boolean? = null,
  val duplicateDelay: Long? = null,
  val scanInterval: Long? = null,
  val supportedFormats: List<BarcodeFormatData?>? = null,
  val scanWindow: ScanWindowData? = null,
  val autoZoom: Boolean? = null,
  val imageQuality: Double? = null,
  val confidenceThreshold: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScannerOptionsData {
      val scanMode = pigeonVar_list[0] as ScanModeData?
      val continuous = pigeonVar_list[1] as Boolean?
      val enableFlash = pigeonVar_list[2] as Boolean?
      val enableGallery = pigeonVar_list[3] as Boolean?
      val enableCameraSwitch = pigeonVar_list[4] as Boolean?
      val enableBeep = pigeonVar_list[5] as Boolean?
      val enableVibration = pigeonVar_list[6] as Boolean?
      val enableImageCapture = pigeonVar_list[7] as Boolean?
      val enableImageAnnotation = pigeonVar_list[8] as Boolean?
      val allowDuplicate = pigeonVar_list[9] as Boolean?
      val duplicateDelay = pigeonVar_list[10] as Long?
      val scanInterval = pigeonVar_list[11] as Long?
      val supportedFormats = pigeonVar_list[12] as List<BarcodeFormatData?>?
      val scanWindow = pigeonVar_list[13] as ScanWindowData?
      val autoZoom = pigeonVar_list[14] as Boolean?
      val imageQuality = pigeonVar_list[15] as Double?
      val confidenceThreshold = pigeonVar_list[16] as Double?
      return ScannerOptionsData(scanMode, continuous, enableFlash, enableGallery, enableCameraSwitch, enableBeep, enableVibration, enableImageCapture, enableImageAnnotation, allowDuplicate, duplicateDelay, scanInterval, supportedFormats, scanWindow, autoZoom, imageQuality, confidenceThreshold)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      scanMode,
      continuous,
      enableFlash,
      enableGallery,
      enableCameraSwitch,
      enableBeep,
      enableVibration,
      enableImageCapture,
      enableImageAnnotation,
      allowDuplicate,
      duplicateDelay,
      scanInterval,
      supportedFormats,
      scanWindow,
      autoZoom,
      imageQuality,
      confidenceThreshold,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ScannerOptionsData
    return MessagesPigeonUtils.deepEquals(this.scanMode, other.scanMode) && MessagesPigeonUtils.deepEquals(this.continuous, other.continuous) && MessagesPigeonUtils.deepEquals(this.enableFlash, other.enableFlash) && MessagesPigeonUtils.deepEquals(this.enableGallery, other.enableGallery) && MessagesPigeonUtils.deepEquals(this.enableCameraSwitch, other.enableCameraSwitch) && MessagesPigeonUtils.deepEquals(this.enableBeep, other.enableBeep) && MessagesPigeonUtils.deepEquals(this.enableVibration, other.enableVibration) && MessagesPigeonUtils.deepEquals(this.enableImageCapture, other.enableImageCapture) && MessagesPigeonUtils.deepEquals(this.enableImageAnnotation, other.enableImageAnnotation) && MessagesPigeonUtils.deepEquals(this.allowDuplicate, other.allowDuplicate) && MessagesPigeonUtils.deepEquals(this.duplicateDelay, other.duplicateDelay) && MessagesPigeonUtils.deepEquals(this.scanInterval, other.scanInterval) && MessagesPigeonUtils.deepEquals(this.supportedFormats, other.supportedFormats) && MessagesPigeonUtils.deepEquals(this.scanWindow, other.scanWindow) && MessagesPigeonUtils.deepEquals(this.autoZoom, other.autoZoom) && MessagesPigeonUtils.deepEquals(this.imageQuality, other.imageQuality) && MessagesPigeonUtils.deepEquals(this.confidenceThreshold, other.confidenceThreshold)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.scanMode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.continuous)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.enableFlash)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.enableGallery)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.enableCameraSwitch)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.enableBeep)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.enableVibration)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.enableImageCapture)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.enableImageAnnotation)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.allowDuplicate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.duplicateDelay)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.scanInterval)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.supportedFormats)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.scanWindow)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.autoZoom)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.imageQuality)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.confidenceThreshold)
    return result
  }
  override fun toString(): String {
    return "ScannerOptionsData(scanMode=$scanMode, continuous=$continuous, enableFlash=$enableFlash, enableGallery=$enableGallery, enableCameraSwitch=$enableCameraSwitch, enableBeep=$enableBeep, enableVibration=$enableVibration, enableImageCapture=$enableImageCapture, enableImageAnnotation=$enableImageAnnotation, allowDuplicate=$allowDuplicate, duplicateDelay=$duplicateDelay, scanInterval=$scanInterval, supportedFormats=$supportedFormats, scanWindow=$scanWindow, autoZoom=$autoZoom, imageQuality=$imageQuality, confidenceThreshold=$confidenceThreshold)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PointData (
  val x: Double? = null,
  val y: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PointData {
      val x = pigeonVar_list[0] as Double?
      val y = pigeonVar_list[1] as Double?
      return PointData(x, y)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      x,
      y,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PointData
    return MessagesPigeonUtils.deepEquals(this.x, other.x) && MessagesPigeonUtils.deepEquals(this.y, other.y)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.x)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.y)
    return result
  }
  override fun toString(): String {
    return "PointData(x=$x, y=$y)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ScannerResultData (
  val value: String? = null,
  val type: String? = null,
  val imageBytes: ByteArray? = null,
  val corners: List<PointData?>? = null,
  val imageWidth: Long? = null,
  val imageHeight: Long? = null,
  val timestamp: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScannerResultData {
      val value = pigeonVar_list[0] as String?
      val type = pigeonVar_list[1] as String?
      val imageBytes = pigeonVar_list[2] as ByteArray?
      val corners = pigeonVar_list[3] as List<PointData?>?
      val imageWidth = pigeonVar_list[4] as Long?
      val imageHeight = pigeonVar_list[5] as Long?
      val timestamp = pigeonVar_list[6] as Long?
      return ScannerResultData(value, type, imageBytes, corners, imageWidth, imageHeight, timestamp)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      value,
      type,
      imageBytes,
      corners,
      imageWidth,
      imageHeight,
      timestamp,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ScannerResultData
    return MessagesPigeonUtils.deepEquals(this.value, other.value) && MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.imageBytes, other.imageBytes) && MessagesPigeonUtils.deepEquals(this.corners, other.corners) && MessagesPigeonUtils.deepEquals(this.imageWidth, other.imageWidth) && MessagesPigeonUtils.deepEquals(this.imageHeight, other.imageHeight) && MessagesPigeonUtils.deepEquals(this.timestamp, other.timestamp)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.value)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.imageBytes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.corners)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.imageWidth)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.imageHeight)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.timestamp)
    return result
  }
  override fun toString(): String {
    return "ScannerResultData(value=$value, type=$type, imageBytes=${imageBytes?.contentToString()}, corners=$corners, imageWidth=$imageWidth, imageHeight=$imageHeight, timestamp=$timestamp)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ScanModeData.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BarcodeFormatData.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScanWindowData.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScannerOptionsData.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PointData.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScannerResultData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ScanModeData -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is BarcodeFormatData -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is ScanWindowData -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ScannerOptionsData -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PointData -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ScannerResultData -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ScannerHostApi {
  fun pause()
  fun resume()
  fun stop()
  fun toggleFlash(): Boolean
  fun switchCamera()
  fun focusAt(x: Double, y: Double)
  fun scanImage(path: String, callback: (Result<List<ScannerResultData?>>) -> Unit)
  fun dispose()

  companion object {
    /** The codec used by ScannerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ScannerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ScannerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.pause$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.pause()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.resume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.resume()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stop()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.toggleFlash$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.toggleFlash())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.switchCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.switchCamera()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.focusAt$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val xArg = args[0] as Double
            val yArg = args[1] as Double
            val wrapped: List<Any?> = try {
              api.focusAt(xArg, yArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.scanImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            api.scanImage(pathArg) { result: Result<List<ScannerResultData?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.dispose()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
