// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum ScanModeData { barcode, qr, all }

enum BarcodeFormatData {
  allFormats,
  code128,
  code39,
  code93,
  codaBar,
  dataMatrix,
  ean13,
  ean8,
  itf,
  qrCode,
  upcA,
  upcE,
  pdf417,
  aztec,
}

class ScanWindowData {
  ScanWindowData({this.widthFactor, this.heightFactor});

  double? widthFactor;

  double? heightFactor;

  List<Object?> _toList() {
    return <Object?>[widthFactor, heightFactor];
  }

  Object encode() {
    return _toList();
  }

  static ScanWindowData decode(Object result) {
    result as List<Object?>;
    return ScanWindowData(
      widthFactor: result[0] as double?,
      heightFactor: result[1] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ScanWindowData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(widthFactor, other.widthFactor) &&
        _deepEquals(heightFactor, other.heightFactor);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ScanWindowData(widthFactor: $widthFactor, heightFactor: $heightFactor)';
  }
}

class ScannerOptionsData {
  ScannerOptionsData({
    this.scanMode,
    this.continuous,
    this.enableFlash,
    this.enableGallery,
    this.enableCameraSwitch,
    this.enableBeep,
    this.enableVibration,
    this.enableImageCapture,
    this.enableImageAnnotation,
    this.allowDuplicate,
    this.duplicateDelay,
    this.scanInterval,
    this.supportedFormats,
    this.scanWindow,
    this.autoZoom,
    this.imageQuality,
    this.confidenceThreshold,
  });

  ScanModeData? scanMode;

  bool? continuous;

  bool? enableFlash;

  bool? enableGallery;

  bool? enableCameraSwitch;

  bool? enableBeep;

  bool? enableVibration;

  bool? enableImageCapture;

  bool? enableImageAnnotation;

  bool? allowDuplicate;

  int? duplicateDelay;

  int? scanInterval;

  List<BarcodeFormatData?>? supportedFormats;

  ScanWindowData? scanWindow;

  bool? autoZoom;

  double? imageQuality;

  double? confidenceThreshold;

  List<Object?> _toList() {
    return <Object?>[
      scanMode,
      continuous,
      enableFlash,
      enableGallery,
      enableCameraSwitch,
      enableBeep,
      enableVibration,
      enableImageCapture,
      enableImageAnnotation,
      allowDuplicate,
      duplicateDelay,
      scanInterval,
      supportedFormats,
      scanWindow,
      autoZoom,
      imageQuality,
      confidenceThreshold,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ScannerOptionsData decode(Object result) {
    result as List<Object?>;
    return ScannerOptionsData(
      scanMode: result[0] as ScanModeData?,
      continuous: result[1] as bool?,
      enableFlash: result[2] as bool?,
      enableGallery: result[3] as bool?,
      enableCameraSwitch: result[4] as bool?,
      enableBeep: result[5] as bool?,
      enableVibration: result[6] as bool?,
      enableImageCapture: result[7] as bool?,
      enableImageAnnotation: result[8] as bool?,
      allowDuplicate: result[9] as bool?,
      duplicateDelay: result[10] as int?,
      scanInterval: result[11] as int?,
      supportedFormats:
          (result[12] as List<Object?>?)?.cast<BarcodeFormatData?>(),
      scanWindow: result[13] as ScanWindowData?,
      autoZoom: result[14] as bool?,
      imageQuality: result[15] as double?,
      confidenceThreshold: result[16] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ScannerOptionsData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(scanMode, other.scanMode) &&
        _deepEquals(continuous, other.continuous) &&
        _deepEquals(enableFlash, other.enableFlash) &&
        _deepEquals(enableGallery, other.enableGallery) &&
        _deepEquals(enableCameraSwitch, other.enableCameraSwitch) &&
        _deepEquals(enableBeep, other.enableBeep) &&
        _deepEquals(enableVibration, other.enableVibration) &&
        _deepEquals(enableImageCapture, other.enableImageCapture) &&
        _deepEquals(enableImageAnnotation, other.enableImageAnnotation) &&
        _deepEquals(allowDuplicate, other.allowDuplicate) &&
        _deepEquals(duplicateDelay, other.duplicateDelay) &&
        _deepEquals(scanInterval, other.scanInterval) &&
        _deepEquals(supportedFormats, other.supportedFormats) &&
        _deepEquals(scanWindow, other.scanWindow) &&
        _deepEquals(autoZoom, other.autoZoom) &&
        _deepEquals(imageQuality, other.imageQuality) &&
        _deepEquals(confidenceThreshold, other.confidenceThreshold);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ScannerOptionsData(scanMode: $scanMode, continuous: $continuous, enableFlash: $enableFlash, enableGallery: $enableGallery, enableCameraSwitch: $enableCameraSwitch, enableBeep: $enableBeep, enableVibration: $enableVibration, enableImageCapture: $enableImageCapture, enableImageAnnotation: $enableImageAnnotation, allowDuplicate: $allowDuplicate, duplicateDelay: $duplicateDelay, scanInterval: $scanInterval, supportedFormats: $supportedFormats, scanWindow: $scanWindow, autoZoom: $autoZoom, imageQuality: $imageQuality, confidenceThreshold: $confidenceThreshold)';
  }
}

class PointData {
  PointData({this.x, this.y});

  double? x;

  double? y;

  List<Object?> _toList() {
    return <Object?>[x, y];
  }

  Object encode() {
    return _toList();
  }

  static PointData decode(Object result) {
    result as List<Object?>;
    return PointData(x: result[0] as double?, y: result[1] as double?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PointData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(x, other.x) && _deepEquals(y, other.y);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PointData(x: $x, y: $y)';
  }
}

class ScannerResultData {
  ScannerResultData({
    this.value,
    this.type,
    this.imageBytes,
    this.corners,
    this.imageWidth,
    this.imageHeight,
    this.timestamp,
  });

  String? value;

  String? type;

  Uint8List? imageBytes;

  List<PointData?>? corners;

  int? imageWidth;

  int? imageHeight;

  int? timestamp;

  List<Object?> _toList() {
    return <Object?>[
      value,
      type,
      imageBytes,
      corners,
      imageWidth,
      imageHeight,
      timestamp,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ScannerResultData decode(Object result) {
    result as List<Object?>;
    return ScannerResultData(
      value: result[0] as String?,
      type: result[1] as String?,
      imageBytes: result[2] as Uint8List?,
      corners: (result[3] as List<Object?>?)?.cast<PointData?>(),
      imageWidth: result[4] as int?,
      imageHeight: result[5] as int?,
      timestamp: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ScannerResultData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(value, other.value) &&
        _deepEquals(type, other.type) &&
        _deepEquals(imageBytes, other.imageBytes) &&
        _deepEquals(corners, other.corners) &&
        _deepEquals(imageWidth, other.imageWidth) &&
        _deepEquals(imageHeight, other.imageHeight) &&
        _deepEquals(timestamp, other.timestamp);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ScannerResultData(value: $value, type: $type, imageBytes: $imageBytes, corners: $corners, imageWidth: $imageWidth, imageHeight: $imageHeight, timestamp: $timestamp)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is ScanModeData) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is BarcodeFormatData) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is ScanWindowData) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is ScannerOptionsData) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is PointData) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is ScannerResultData) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : ScanModeData.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : BarcodeFormatData.values[value];
      case 131:
        return ScanWindowData.decode(readValue(buffer)!);
      case 132:
        return ScannerOptionsData.decode(readValue(buffer)!);
      case 133:
        return PointData.decode(readValue(buffer)!);
      case 134:
        return ScannerResultData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ScannerHostApi {
  /// Constructor for [ScannerHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ScannerHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  })  : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> pause() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.pause$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> resume() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.resume$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> stop() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<bool> toggleFlash() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.toggleFlash$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> switchCamera() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.switchCamera$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> focusAt(double x, double y) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.focusAt$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[x, y],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<List<ScannerResultData?>> scanImage(String path) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.scanImage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[path],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<ScannerResultData?>();
  }

  Future<void> dispose() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}
