// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

enum ScanModeData {
  barcode,
  qr,
  all,
}

enum BarcodeFormatData {
  allFormats,
  code128,
  code39,
  code93,
  codaBar,
  dataMatrix,
  ean13,
  ean8,
  itf,
  qrCode,
  upcA,
  upcE,
  pdf417,
  aztec,
}

class ScanWindowData {
  ScanWindowData({
    this.widthFactor,
    this.heightFactor,
  });

  double? widthFactor;

  double? heightFactor;

  Object encode() {
    return <Object?>[
      widthFactor,
      heightFactor,
    ];
  }

  static ScanWindowData decode(Object result) {
    result as List<Object?>;
    return ScanWindowData(
      widthFactor: result[0] as double?,
      heightFactor: result[1] as double?,
    );
  }
}

class ScannerOptionsData {
  ScannerOptionsData({
    this.scanMode,
    this.continuous,
    this.enableFlash,
    this.enableGallery,
    this.enableCameraSwitch,
    this.enableBeep,
    this.enableVibration,
    this.enableImageCapture,
    this.enableImageAnnotation,
    this.allowDuplicate,
    this.duplicateDelay,
    this.scanInterval,
    this.supportedFormats,
    this.scanWindow,
    this.autoZoom,
    this.imageQuality,
    this.confidenceThreshold,
  });

  ScanModeData? scanMode;

  bool? continuous;

  bool? enableFlash;

  bool? enableGallery;

  bool? enableCameraSwitch;

  bool? enableBeep;

  bool? enableVibration;

  bool? enableImageCapture;

  bool? enableImageAnnotation;

  bool? allowDuplicate;

  int? duplicateDelay;

  int? scanInterval;

  List<BarcodeFormatData?>? supportedFormats;

  ScanWindowData? scanWindow;

  bool? autoZoom;

  double? imageQuality;

  double? confidenceThreshold;

  Object encode() {
    return <Object?>[
      scanMode,
      continuous,
      enableFlash,
      enableGallery,
      enableCameraSwitch,
      enableBeep,
      enableVibration,
      enableImageCapture,
      enableImageAnnotation,
      allowDuplicate,
      duplicateDelay,
      scanInterval,
      supportedFormats,
      scanWindow,
      autoZoom,
      imageQuality,
      confidenceThreshold,
    ];
  }

  static ScannerOptionsData decode(Object result) {
    result as List<Object?>;
    return ScannerOptionsData(
      scanMode: result[0] as ScanModeData?,
      continuous: result[1] as bool?,
      enableFlash: result[2] as bool?,
      enableGallery: result[3] as bool?,
      enableCameraSwitch: result[4] as bool?,
      enableBeep: result[5] as bool?,
      enableVibration: result[6] as bool?,
      enableImageCapture: result[7] as bool?,
      enableImageAnnotation: result[8] as bool?,
      allowDuplicate: result[9] as bool?,
      duplicateDelay: result[10] as int?,
      scanInterval: result[11] as int?,
      supportedFormats: (result[12] as List<Object?>?)?.cast<BarcodeFormatData?>(),
      scanWindow: result[13] as ScanWindowData?,
      autoZoom: result[14] as bool?,
      imageQuality: result[15] as double?,
      confidenceThreshold: result[16] as double?,
    );
  }
}

class PointData {
  PointData({
    this.x,
    this.y,
  });

  double? x;

  double? y;

  Object encode() {
    return <Object?>[
      x,
      y,
    ];
  }

  static PointData decode(Object result) {
    result as List<Object?>;
    return PointData(
      x: result[0] as double?,
      y: result[1] as double?,
    );
  }
}

class ScannerResultData {
  ScannerResultData({
    this.value,
    this.type,
    this.imageBytes,
    this.corners,
    this.imageWidth,
    this.imageHeight,
    this.timestamp,
    this.imageRejected,
    this.sharpnessScore,
  });

  String? value;

  String? type;

  Uint8List? imageBytes;

  List<PointData?>? corners;

  int? imageWidth;

  int? imageHeight;

  int? timestamp;

  bool? imageRejected;

  double? sharpnessScore;

  Object encode() {
    return <Object?>[
      value,
      type,
      imageBytes,
      corners,
      imageWidth,
      imageHeight,
      timestamp,
      imageRejected,
      sharpnessScore,
    ];
  }

  static ScannerResultData decode(Object result) {
    result as List<Object?>;
    return ScannerResultData(
      value: result[0] as String?,
      type: result[1] as String?,
      imageBytes: result[2] as Uint8List?,
      corners: (result[3] as List<Object?>?)?.cast<PointData?>(),
      imageWidth: result[4] as int?,
      imageHeight: result[5] as int?,
      timestamp: result[6] as int?,
      imageRejected: result[7] as bool?,
      sharpnessScore: result[8] as double?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ScanModeData) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is BarcodeFormatData) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is ScanWindowData) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is ScannerOptionsData) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is PointData) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is ScannerResultData) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ScanModeData.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : BarcodeFormatData.values[value];
      case 131: 
        return ScanWindowData.decode(readValue(buffer)!);
      case 132: 
        return ScannerOptionsData.decode(readValue(buffer)!);
      case 133: 
        return PointData.decode(readValue(buffer)!);
      case 134: 
        return ScannerResultData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ScannerHostApi {
  /// Constructor for [ScannerHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ScannerHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> pause() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.pause$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> resume() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.resume$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stop() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.stop$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool> toggleFlash() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.toggleFlash$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<void> switchCamera() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.switchCamera$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> focusAt(double x, double y) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.focusAt$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[x, y]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<List<ScannerResultData?>> scanImage(String path) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.scanImage$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<ScannerResultData?>();
    }
  }

  Future<void> dispose() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.dispose$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
