// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum ScanModeData: Int, CaseIterable {
  case barcode = 0
  case qr = 1
  case all = 2
}

enum BarcodeFormatData: Int, CaseIterable {
  case allFormats = 0
  case code128 = 1
  case code39 = 2
  case code93 = 3
  case codaBar = 4
  case dataMatrix = 5
  case ean13 = 6
  case ean8 = 7
  case itf = 8
  case qrCode = 9
  case upcA = 10
  case upcE = 11
  case pdf417 = 12
  case aztec = 13
}

/// Generated class from Pigeon that represents data sent in messages.
struct ScanWindowData: Hashable, CustomStringConvertible {
  var widthFactor: Double? = nil
  var heightFactor: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScanWindowData? {
    let widthFactor: Double? = nilOrValue(pigeonVar_list[0])
    let heightFactor: Double? = nilOrValue(pigeonVar_list[1])

    return ScanWindowData(
      widthFactor: widthFactor,
      heightFactor: heightFactor
    )
  }
  func toList() -> [Any?] {
    return [
      widthFactor,
      heightFactor,
    ]
  }
  static func == (lhs: ScanWindowData, rhs: ScanWindowData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.widthFactor, rhs.widthFactor) && MessagesPigeonInternal.deepEquals(lhs.heightFactor, rhs.heightFactor)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ScanWindowData")
    MessagesPigeonInternal.deepHash(value: widthFactor, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: heightFactor, hasher: &hasher)
  }

  public var description: String {
    return "ScanWindowData(widthFactor: \(String(describing: widthFactor)), heightFactor: \(String(describing: heightFactor)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ScannerOptionsData: Hashable, CustomStringConvertible {
  var scanMode: ScanModeData? = nil
  var continuous: Bool? = nil
  var enableFlash: Bool? = nil
  var enableGallery: Bool? = nil
  var enableCameraSwitch: Bool? = nil
  var enableBeep: Bool? = nil
  var enableVibration: Bool? = nil
  var enableImageCapture: Bool? = nil
  var enableImageAnnotation: Bool? = nil
  var allowDuplicate: Bool? = nil
  var duplicateDelay: Int64? = nil
  var scanInterval: Int64? = nil
  var supportedFormats: [BarcodeFormatData?]? = nil
  var scanWindow: ScanWindowData? = nil
  var autoZoom: Bool? = nil
  var imageQuality: Double? = nil
  var confidenceThreshold: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScannerOptionsData? {
    let scanMode: ScanModeData? = nilOrValue(pigeonVar_list[0])
    let continuous: Bool? = nilOrValue(pigeonVar_list[1])
    let enableFlash: Bool? = nilOrValue(pigeonVar_list[2])
    let enableGallery: Bool? = nilOrValue(pigeonVar_list[3])
    let enableCameraSwitch: Bool? = nilOrValue(pigeonVar_list[4])
    let enableBeep: Bool? = nilOrValue(pigeonVar_list[5])
    let enableVibration: Bool? = nilOrValue(pigeonVar_list[6])
    let enableImageCapture: Bool? = nilOrValue(pigeonVar_list[7])
    let enableImageAnnotation: Bool? = nilOrValue(pigeonVar_list[8])
    let allowDuplicate: Bool? = nilOrValue(pigeonVar_list[9])
    let duplicateDelay: Int64? = nilOrValue(pigeonVar_list[10])
    let scanInterval: Int64? = nilOrValue(pigeonVar_list[11])
    let supportedFormats: [BarcodeFormatData?]? = nilOrValue(pigeonVar_list[12])
    let scanWindow: ScanWindowData? = nilOrValue(pigeonVar_list[13])
    let autoZoom: Bool? = nilOrValue(pigeonVar_list[14])
    let imageQuality: Double? = nilOrValue(pigeonVar_list[15])
    let confidenceThreshold: Double? = nilOrValue(pigeonVar_list[16])

    return ScannerOptionsData(
      scanMode: scanMode,
      continuous: continuous,
      enableFlash: enableFlash,
      enableGallery: enableGallery,
      enableCameraSwitch: enableCameraSwitch,
      enableBeep: enableBeep,
      enableVibration: enableVibration,
      enableImageCapture: enableImageCapture,
      enableImageAnnotation: enableImageAnnotation,
      allowDuplicate: allowDuplicate,
      duplicateDelay: duplicateDelay,
      scanInterval: scanInterval,
      supportedFormats: supportedFormats,
      scanWindow: scanWindow,
      autoZoom: autoZoom,
      imageQuality: imageQuality,
      confidenceThreshold: confidenceThreshold
    )
  }
  func toList() -> [Any?] {
    return [
      scanMode,
      continuous,
      enableFlash,
      enableGallery,
      enableCameraSwitch,
      enableBeep,
      enableVibration,
      enableImageCapture,
      enableImageAnnotation,
      allowDuplicate,
      duplicateDelay,
      scanInterval,
      supportedFormats,
      scanWindow,
      autoZoom,
      imageQuality,
      confidenceThreshold,
    ]
  }
  static func == (lhs: ScannerOptionsData, rhs: ScannerOptionsData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.scanMode, rhs.scanMode) && MessagesPigeonInternal.deepEquals(lhs.continuous, rhs.continuous) && MessagesPigeonInternal.deepEquals(lhs.enableFlash, rhs.enableFlash) && MessagesPigeonInternal.deepEquals(lhs.enableGallery, rhs.enableGallery) && MessagesPigeonInternal.deepEquals(lhs.enableCameraSwitch, rhs.enableCameraSwitch) && MessagesPigeonInternal.deepEquals(lhs.enableBeep, rhs.enableBeep) && MessagesPigeonInternal.deepEquals(lhs.enableVibration, rhs.enableVibration) && MessagesPigeonInternal.deepEquals(lhs.enableImageCapture, rhs.enableImageCapture) && MessagesPigeonInternal.deepEquals(lhs.enableImageAnnotation, rhs.enableImageAnnotation) && MessagesPigeonInternal.deepEquals(lhs.allowDuplicate, rhs.allowDuplicate) && MessagesPigeonInternal.deepEquals(lhs.duplicateDelay, rhs.duplicateDelay) && MessagesPigeonInternal.deepEquals(lhs.scanInterval, rhs.scanInterval) && MessagesPigeonInternal.deepEquals(lhs.supportedFormats, rhs.supportedFormats) && MessagesPigeonInternal.deepEquals(lhs.scanWindow, rhs.scanWindow) && MessagesPigeonInternal.deepEquals(lhs.autoZoom, rhs.autoZoom) && MessagesPigeonInternal.deepEquals(lhs.imageQuality, rhs.imageQuality) && MessagesPigeonInternal.deepEquals(lhs.confidenceThreshold, rhs.confidenceThreshold)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ScannerOptionsData")
    MessagesPigeonInternal.deepHash(value: scanMode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: continuous, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: enableFlash, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: enableGallery, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: enableCameraSwitch, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: enableBeep, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: enableVibration, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: enableImageCapture, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: enableImageAnnotation, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: allowDuplicate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: duplicateDelay, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: scanInterval, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: supportedFormats, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: scanWindow, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: autoZoom, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: imageQuality, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: confidenceThreshold, hasher: &hasher)
  }

  public var description: String {
    return "ScannerOptionsData(scanMode: \(String(describing: scanMode)), continuous: \(String(describing: continuous)), enableFlash: \(String(describing: enableFlash)), enableGallery: \(String(describing: enableGallery)), enableCameraSwitch: \(String(describing: enableCameraSwitch)), enableBeep: \(String(describing: enableBeep)), enableVibration: \(String(describing: enableVibration)), enableImageCapture: \(String(describing: enableImageCapture)), enableImageAnnotation: \(String(describing: enableImageAnnotation)), allowDuplicate: \(String(describing: allowDuplicate)), duplicateDelay: \(String(describing: duplicateDelay)), scanInterval: \(String(describing: scanInterval)), supportedFormats: \(String(describing: supportedFormats)), scanWindow: \(String(describing: scanWindow)), autoZoom: \(String(describing: autoZoom)), imageQuality: \(String(describing: imageQuality)), confidenceThreshold: \(String(describing: confidenceThreshold)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PointData: Hashable, CustomStringConvertible {
  var x: Double? = nil
  var y: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PointData? {
    let x: Double? = nilOrValue(pigeonVar_list[0])
    let y: Double? = nilOrValue(pigeonVar_list[1])

    return PointData(
      x: x,
      y: y
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
    ]
  }
  static func == (lhs: PointData, rhs: PointData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.x, rhs.x) && MessagesPigeonInternal.deepEquals(lhs.y, rhs.y)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PointData")
    MessagesPigeonInternal.deepHash(value: x, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: y, hasher: &hasher)
  }

  public var description: String {
    return "PointData(x: \(String(describing: x)), y: \(String(describing: y)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ScannerResultData: Hashable, CustomStringConvertible {
  var value: String? = nil
  var type: String? = nil
  var imageBytes: FlutterStandardTypedData? = nil
  var corners: [PointData?]? = nil
  var imageWidth: Int64? = nil
  var imageHeight: Int64? = nil
  var timestamp: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScannerResultData? {
    let value: String? = nilOrValue(pigeonVar_list[0])
    let type: String? = nilOrValue(pigeonVar_list[1])
    let imageBytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[2])
    let corners: [PointData?]? = nilOrValue(pigeonVar_list[3])
    let imageWidth: Int64? = nilOrValue(pigeonVar_list[4])
    let imageHeight: Int64? = nilOrValue(pigeonVar_list[5])
    let timestamp: Int64? = nilOrValue(pigeonVar_list[6])

    return ScannerResultData(
      value: value,
      type: type,
      imageBytes: imageBytes,
      corners: corners,
      imageWidth: imageWidth,
      imageHeight: imageHeight,
      timestamp: timestamp
    )
  }
  func toList() -> [Any?] {
    return [
      value,
      type,
      imageBytes,
      corners,
      imageWidth,
      imageHeight,
      timestamp,
    ]
  }
  static func == (lhs: ScannerResultData, rhs: ScannerResultData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.value, rhs.value) && MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.imageBytes, rhs.imageBytes) && MessagesPigeonInternal.deepEquals(lhs.corners, rhs.corners) && MessagesPigeonInternal.deepEquals(lhs.imageWidth, rhs.imageWidth) && MessagesPigeonInternal.deepEquals(lhs.imageHeight, rhs.imageHeight) && MessagesPigeonInternal.deepEquals(lhs.timestamp, rhs.timestamp)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ScannerResultData")
    MessagesPigeonInternal.deepHash(value: value, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: imageBytes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: corners, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: imageWidth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: imageHeight, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: timestamp, hasher: &hasher)
  }

  public var description: String {
    return "ScannerResultData(value: \(String(describing: value)), type: \(String(describing: type)), imageBytes: \(String(describing: imageBytes)), corners: \(String(describing: corners)), imageWidth: \(String(describing: imageWidth)), imageHeight: \(String(describing: imageHeight)), timestamp: \(String(describing: timestamp)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ScanModeData(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BarcodeFormatData(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return ScanWindowData.fromList(self.readValue() as! [Any?])
    case 132:
      return ScannerOptionsData.fromList(self.readValue() as! [Any?])
    case 133:
      return PointData.fromList(self.readValue() as! [Any?])
    case 134:
      return ScannerResultData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ScanModeData {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? BarcodeFormatData {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? ScanWindowData {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? ScannerOptionsData {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PointData {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? ScannerResultData {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ScannerHostApi {
  func pause() throws
  func resume() throws
  func stop() throws
  func toggleFlash() throws -> Bool
  func switchCamera() throws
  func focusAt(x: Double, y: Double) throws
  func scanImage(path: String, completion: @escaping (Result<[ScannerResultData?], Error>) -> Void)
  func dispose() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ScannerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ScannerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ScannerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.pause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { _, reply in
        do {
          try api.pause()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    let resumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.resume\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeChannel.setMessageHandler { _, reply in
        do {
          try api.resume()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resumeChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          try api.stop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    let toggleFlashChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.toggleFlash\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      toggleFlashChannel.setMessageHandler { _, reply in
        do {
          let result = try api.toggleFlash()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      toggleFlashChannel.setMessageHandler(nil)
    }
    let switchCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.switchCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      switchCameraChannel.setMessageHandler { _, reply in
        do {
          try api.switchCamera()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      switchCameraChannel.setMessageHandler(nil)
    }
    let focusAtChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.focusAt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      focusAtChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let xArg = args[0] as! Double
        let yArg = args[1] as! Double
        do {
          try api.focusAt(x: xArg, y: yArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      focusAtChannel.setMessageHandler(nil)
    }
    let scanImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.scanImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      scanImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        api.scanImage(path: pathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      scanImageChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_full_screen_scanner_platform_interface.ScannerHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        do {
          try api.dispose()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
